package com.treasure.auto.entity;

import java.util.Date;

public class Buy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.buy_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer buy_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.start_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Short start_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.end_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Short end_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.ticket_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date ticket_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.end_flag
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean end_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.user_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.buy_id
     *
     * @return the value of buy.buy_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getBuy_id() {
        return buy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.buy_id
     *
     * @param buy_id the value for buy.buy_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setBuy_id(Integer buy_id) {
        this.buy_id = buy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.start_no
     *
     * @return the value of buy.start_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Short getStart_no() {
        return start_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.start_no
     *
     * @param start_no the value for buy.start_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setStart_no(Short start_no) {
        this.start_no = start_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.end_no
     *
     * @return the value of buy.end_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Short getEnd_no() {
        return end_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.end_no
     *
     * @param end_no the value for buy.end_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setEnd_no(Short end_no) {
        this.end_no = end_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.ticket_date
     *
     * @return the value of buy.ticket_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getTicket_date() {
        return ticket_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.ticket_date
     *
     * @param ticket_date the value for buy.ticket_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setTicket_date(Date ticket_date) {
        this.ticket_date = ticket_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.end_flag
     *
     * @return the value of buy.end_flag
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getEnd_flag() {
        return end_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.end_flag
     *
     * @param end_flag the value for buy.end_flag
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setEnd_flag(Boolean end_flag) {
        this.end_flag = end_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.user_id
     *
     * @return the value of buy.user_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.user_id
     *
     * @param user_id the value for buy.user_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}