package com.treasure.auto.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BuyItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.buy_item_id
     *
     * @mbg.generated
     */
    private Integer buyItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.item_flag
     *
     * @mbg.generated
     */
    private Boolean itemFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.buy_money
     *
     * @mbg.generated
     */
    private BigDecimal buyMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.ticket_id
     *
     * @mbg.generated
     */
    private Integer ticketId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.buy_item_id
     *
     * @return the value of buy_item.buy_item_id
     *
     * @mbg.generated
     */
    public Integer getBuyItemId() {
        return buyItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.buy_item_id
     *
     * @param buyItemId the value for buy_item.buy_item_id
     *
     * @mbg.generated
     */
    public void setBuyItemId(Integer buyItemId) {
        this.buyItemId = buyItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.user_id
     *
     * @return the value of buy_item.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.user_id
     *
     * @param userId the value for buy_item.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.create_time
     *
     * @return the value of buy_item.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.create_time
     *
     * @param createTime the value for buy_item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.update_time
     *
     * @return the value of buy_item.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.update_time
     *
     * @param updateTime the value for buy_item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.item_flag
     *
     * @return the value of buy_item.item_flag
     *
     * @mbg.generated
     */
    public Boolean getItemFlag() {
        return itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.item_flag
     *
     * @param itemFlag the value for buy_item.item_flag
     *
     * @mbg.generated
     */
    public void setItemFlag(Boolean itemFlag) {
        this.itemFlag = itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.buy_money
     *
     * @return the value of buy_item.buy_money
     *
     * @mbg.generated
     */
    public BigDecimal getBuyMoney() {
        return buyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.buy_money
     *
     * @param buyMoney the value for buy_item.buy_money
     *
     * @mbg.generated
     */
    public void setBuyMoney(BigDecimal buyMoney) {
        this.buyMoney = buyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.ticket_id
     *
     * @return the value of buy_item.ticket_id
     *
     * @mbg.generated
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.ticket_id
     *
     * @param ticketId the value for buy_item.ticket_id
     *
     * @mbg.generated
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }
}