package com.treasure.auto.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BuyItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.buy_item_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer buy_item_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.buy_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer buy_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.create_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.update_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.item_flag
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean item_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.buy_money
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private BigDecimal buy_money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_item.ticket_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer ticket_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.buy_item_id
     *
     * @return the value of buy_item.buy_item_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getBuy_item_id() {
        return buy_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.buy_item_id
     *
     * @param buy_item_id the value for buy_item.buy_item_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setBuy_item_id(Integer buy_item_id) {
        this.buy_item_id = buy_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.buy_id
     *
     * @return the value of buy_item.buy_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getBuy_id() {
        return buy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.buy_id
     *
     * @param buy_id the value for buy_item.buy_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setBuy_id(Integer buy_id) {
        this.buy_id = buy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.create_time
     *
     * @return the value of buy_item.create_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.create_time
     *
     * @param create_time the value for buy_item.create_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.update_time
     *
     * @return the value of buy_item.update_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.update_time
     *
     * @param update_time the value for buy_item.update_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.item_flag
     *
     * @return the value of buy_item.item_flag
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getItem_flag() {
        return item_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.item_flag
     *
     * @param item_flag the value for buy_item.item_flag
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setItem_flag(Boolean item_flag) {
        this.item_flag = item_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.buy_money
     *
     * @return the value of buy_item.buy_money
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public BigDecimal getBuy_money() {
        return buy_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.buy_money
     *
     * @param buy_money the value for buy_item.buy_money
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setBuy_money(BigDecimal buy_money) {
        this.buy_money = buy_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_item.ticket_id
     *
     * @return the value of buy_item.ticket_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getTicket_id() {
        return ticket_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_item.ticket_id
     *
     * @param ticket_id the value for buy_item.ticket_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setTicket_id(Integer ticket_id) {
        this.ticket_id = ticket_id;
    }
}