package com.treasure.auto.entity;

import java.util.Date;

public class Bz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.bz_id
     *
     * @mbg.generated
     */
    private Integer bzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.count_num
     *
     * @mbg.generated
     */
    private Short countNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.bz_date
     *
     * @mbg.generated
     */
    private Date bzDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.bz_type_code
     *
     * @mbg.generated
     */
    private String bzTypeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.bz_id
     *
     * @return the value of bz.bz_id
     *
     * @mbg.generated
     */
    public Integer getBzId() {
        return bzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.bz_id
     *
     * @param bzId the value for bz.bz_id
     *
     * @mbg.generated
     */
    public void setBzId(Integer bzId) {
        this.bzId = bzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.count_num
     *
     * @return the value of bz.count_num
     *
     * @mbg.generated
     */
    public Short getCountNum() {
        return countNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.count_num
     *
     * @param countNum the value for bz.count_num
     *
     * @mbg.generated
     */
    public void setCountNum(Short countNum) {
        this.countNum = countNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.bz_date
     *
     * @return the value of bz.bz_date
     *
     * @mbg.generated
     */
    public Date getBzDate() {
        return bzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.bz_date
     *
     * @param bzDate the value for bz.bz_date
     *
     * @mbg.generated
     */
    public void setBzDate(Date bzDate) {
        this.bzDate = bzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.bz_type_code
     *
     * @return the value of bz.bz_type_code
     *
     * @mbg.generated
     */
    public String getBzTypeCode() {
        return bzTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.bz_type_code
     *
     * @param bzTypeCode the value for bz.bz_type_code
     *
     * @mbg.generated
     */
    public void setBzTypeCode(String bzTypeCode) {
        this.bzTypeCode = bzTypeCode == null ? null : bzTypeCode.trim();
    }
}