package com.treasure.auto.entity;

import java.util.Date;

public class Bz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.bz_id
     *
     * @mbg.generated
     */
    private Integer bzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.bz_date
     *
     * @mbg.generated
     */
    private Date bzDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.bsg
     *
     * @mbg.generated
     */
    private Short bsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.qbg
     *
     * @mbg.generated
     */
    private Short qbg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.qbs
     *
     * @mbg.generated
     */
    private Short qbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.qsg
     *
     * @mbg.generated
     */
    private Short qsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wbg
     *
     * @mbg.generated
     */
    private Short wbg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wbs
     *
     * @mbg.generated
     */
    private Short wbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wqb
     *
     * @mbg.generated
     */
    private Short wqb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wqg
     *
     * @mbg.generated
     */
    private Short wqg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wqs
     *
     * @mbg.generated
     */
    private Short wqs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wsg
     *
     * @mbg.generated
     */
    private Short wsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wxzs
     *
     * @mbg.generated
     */
    private Short wxzs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz.wxzw
     *
     * @mbg.generated
     */
    private Short wxzw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.bz_id
     *
     * @return the value of bz.bz_id
     *
     * @mbg.generated
     */
    public Integer getBzId() {
        return bzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.bz_id
     *
     * @param bzId the value for bz.bz_id
     *
     * @mbg.generated
     */
    public void setBzId(Integer bzId) {
        this.bzId = bzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.bz_date
     *
     * @return the value of bz.bz_date
     *
     * @mbg.generated
     */
    public Date getBzDate() {
        return bzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.bz_date
     *
     * @param bzDate the value for bz.bz_date
     *
     * @mbg.generated
     */
    public void setBzDate(Date bzDate) {
        this.bzDate = bzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.bsg
     *
     * @return the value of bz.bsg
     *
     * @mbg.generated
     */
    public Short getBsg() {
        return bsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.bsg
     *
     * @param bsg the value for bz.bsg
     *
     * @mbg.generated
     */
    public void setBsg(Short bsg) {
        this.bsg = bsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.qbg
     *
     * @return the value of bz.qbg
     *
     * @mbg.generated
     */
    public Short getQbg() {
        return qbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.qbg
     *
     * @param qbg the value for bz.qbg
     *
     * @mbg.generated
     */
    public void setQbg(Short qbg) {
        this.qbg = qbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.qbs
     *
     * @return the value of bz.qbs
     *
     * @mbg.generated
     */
    public Short getQbs() {
        return qbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.qbs
     *
     * @param qbs the value for bz.qbs
     *
     * @mbg.generated
     */
    public void setQbs(Short qbs) {
        this.qbs = qbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.qsg
     *
     * @return the value of bz.qsg
     *
     * @mbg.generated
     */
    public Short getQsg() {
        return qsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.qsg
     *
     * @param qsg the value for bz.qsg
     *
     * @mbg.generated
     */
    public void setQsg(Short qsg) {
        this.qsg = qsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wbg
     *
     * @return the value of bz.wbg
     *
     * @mbg.generated
     */
    public Short getWbg() {
        return wbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wbg
     *
     * @param wbg the value for bz.wbg
     *
     * @mbg.generated
     */
    public void setWbg(Short wbg) {
        this.wbg = wbg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wbs
     *
     * @return the value of bz.wbs
     *
     * @mbg.generated
     */
    public Short getWbs() {
        return wbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wbs
     *
     * @param wbs the value for bz.wbs
     *
     * @mbg.generated
     */
    public void setWbs(Short wbs) {
        this.wbs = wbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wqb
     *
     * @return the value of bz.wqb
     *
     * @mbg.generated
     */
    public Short getWqb() {
        return wqb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wqb
     *
     * @param wqb the value for bz.wqb
     *
     * @mbg.generated
     */
    public void setWqb(Short wqb) {
        this.wqb = wqb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wqg
     *
     * @return the value of bz.wqg
     *
     * @mbg.generated
     */
    public Short getWqg() {
        return wqg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wqg
     *
     * @param wqg the value for bz.wqg
     *
     * @mbg.generated
     */
    public void setWqg(Short wqg) {
        this.wqg = wqg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wqs
     *
     * @return the value of bz.wqs
     *
     * @mbg.generated
     */
    public Short getWqs() {
        return wqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wqs
     *
     * @param wqs the value for bz.wqs
     *
     * @mbg.generated
     */
    public void setWqs(Short wqs) {
        this.wqs = wqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wsg
     *
     * @return the value of bz.wsg
     *
     * @mbg.generated
     */
    public Short getWsg() {
        return wsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wsg
     *
     * @param wsg the value for bz.wsg
     *
     * @mbg.generated
     */
    public void setWsg(Short wsg) {
        this.wsg = wsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wxzs
     *
     * @return the value of bz.wxzs
     *
     * @mbg.generated
     */
    public Short getWxzs() {
        return wxzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wxzs
     *
     * @param wxzs the value for bz.wxzs
     *
     * @mbg.generated
     */
    public void setWxzs(Short wxzs) {
        this.wxzs = wxzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz.wxzw
     *
     * @return the value of bz.wxzw
     *
     * @mbg.generated
     */
    public Short getWxzw() {
        return wxzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz.wxzw
     *
     * @param wxzw the value for bz.wxzw
     *
     * @mbg.generated
     */
    public void setWxzw(Short wxzw) {
        this.wxzw = wxzw;
    }
}