package com.treasure.auto.entity;

public class BzType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz_type.bz_type_code
     *
     * @mbg.generated
     */
    private String bzTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bz_type.bz_type_name
     *
     * @mbg.generated
     */
    private String bzTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz_type.bz_type_code
     *
     * @return the value of bz_type.bz_type_code
     *
     * @mbg.generated
     */
    public String getBzTypeCode() {
        return bzTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz_type.bz_type_code
     *
     * @param bzTypeCode the value for bz_type.bz_type_code
     *
     * @mbg.generated
     */
    public void setBzTypeCode(String bzTypeCode) {
        this.bzTypeCode = bzTypeCode == null ? null : bzTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bz_type.bz_type_name
     *
     * @return the value of bz_type.bz_type_name
     *
     * @mbg.generated
     */
    public String getBzTypeName() {
        return bzTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bz_type.bz_type_name
     *
     * @param bzTypeName the value for bz_type.bz_type_name
     *
     * @mbg.generated
     */
    public void setBzTypeName(String bzTypeName) {
        this.bzTypeName = bzTypeName == null ? null : bzTypeName.trim();
    }
}