package com.treasure.auto.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SscUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.user_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.username
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.money
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.create_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.update_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.now_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private String now_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.now_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date now_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.user_id
     *
     * @return the value of ssc_user.user_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.user_id
     *
     * @param user_id the value for ssc_user.user_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.username
     *
     * @return the value of ssc_user.username
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.username
     *
     * @param username the value for ssc_user.username
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.money
     *
     * @return the value of ssc_user.money
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.money
     *
     * @param money the value for ssc_user.money
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.create_time
     *
     * @return the value of ssc_user.create_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.create_time
     *
     * @param create_time the value for ssc_user.create_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.update_time
     *
     * @return the value of ssc_user.update_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.update_time
     *
     * @param update_time the value for ssc_user.update_time
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.now_no
     *
     * @return the value of ssc_user.now_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public String getNow_no() {
        return now_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.now_no
     *
     * @param now_no the value for ssc_user.now_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setNow_no(String now_no) {
        this.now_no = now_no == null ? null : now_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.now_date
     *
     * @return the value of ssc_user.now_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getNow_date() {
        return now_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.now_date
     *
     * @param now_date the value for ssc_user.now_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setNow_date(Date now_date) {
        this.now_date = now_date;
    }
}