package com.treasure.auto.entity;

import java.util.Date;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_id
     *
     * @mbg.generated
     */
    private Integer ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_no
     *
     * @mbg.generated
     */
    private String ticketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_num
     *
     * @mbg.generated
     */
    private String ticketNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_date
     *
     * @mbg.generated
     */
    private Date ticketDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.bef3_max_count
     *
     * @mbg.generated
     */
    private Boolean bef3MaxCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.mid3_max_count
     *
     * @mbg.generated
     */
    private Boolean mid3MaxCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.aft3_max_count
     *
     * @mbg.generated
     */
    private Boolean aft3MaxCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.max_count
     *
     * @mbg.generated
     */
    private Boolean maxCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.line
     *
     * @mbg.generated
     */
    private Boolean line;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_id
     *
     * @return the value of ticket.ticket_id
     *
     * @mbg.generated
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_id
     *
     * @param ticketId the value for ticket.ticket_id
     *
     * @mbg.generated
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_no
     *
     * @return the value of ticket.ticket_no
     *
     * @mbg.generated
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_no
     *
     * @param ticketNo the value for ticket.ticket_no
     *
     * @mbg.generated
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_num
     *
     * @return the value of ticket.ticket_num
     *
     * @mbg.generated
     */
    public String getTicketNum() {
        return ticketNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_num
     *
     * @param ticketNum the value for ticket.ticket_num
     *
     * @mbg.generated
     */
    public void setTicketNum(String ticketNum) {
        this.ticketNum = ticketNum == null ? null : ticketNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_date
     *
     * @return the value of ticket.ticket_date
     *
     * @mbg.generated
     */
    public Date getTicketDate() {
        return ticketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_date
     *
     * @param ticketDate the value for ticket.ticket_date
     *
     * @mbg.generated
     */
    public void setTicketDate(Date ticketDate) {
        this.ticketDate = ticketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.bef3_max_count
     *
     * @return the value of ticket.bef3_max_count
     *
     * @mbg.generated
     */
    public Boolean getBef3MaxCount() {
        return bef3MaxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.bef3_max_count
     *
     * @param bef3MaxCount the value for ticket.bef3_max_count
     *
     * @mbg.generated
     */
    public void setBef3MaxCount(Boolean bef3MaxCount) {
        this.bef3MaxCount = bef3MaxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.mid3_max_count
     *
     * @return the value of ticket.mid3_max_count
     *
     * @mbg.generated
     */
    public Boolean getMid3MaxCount() {
        return mid3MaxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.mid3_max_count
     *
     * @param mid3MaxCount the value for ticket.mid3_max_count
     *
     * @mbg.generated
     */
    public void setMid3MaxCount(Boolean mid3MaxCount) {
        this.mid3MaxCount = mid3MaxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.aft3_max_count
     *
     * @return the value of ticket.aft3_max_count
     *
     * @mbg.generated
     */
    public Boolean getAft3MaxCount() {
        return aft3MaxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.aft3_max_count
     *
     * @param aft3MaxCount the value for ticket.aft3_max_count
     *
     * @mbg.generated
     */
    public void setAft3MaxCount(Boolean aft3MaxCount) {
        this.aft3MaxCount = aft3MaxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.max_count
     *
     * @return the value of ticket.max_count
     *
     * @mbg.generated
     */
    public Boolean getMaxCount() {
        return maxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.max_count
     *
     * @param maxCount the value for ticket.max_count
     *
     * @mbg.generated
     */
    public void setMaxCount(Boolean maxCount) {
        this.maxCount = maxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.line
     *
     * @return the value of ticket.line
     *
     * @mbg.generated
     */
    public Boolean getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.line
     *
     * @param line the value for ticket.line
     *
     * @mbg.generated
     */
    public void setLine(Boolean line) {
        this.line = line;
    }
}