package com.treasure.auto.entity;

import java.util.Date;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Integer ticket_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private String ticket_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_num
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private String ticket_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Date ticket_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.bef3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean bef3_max_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.mid3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean mid3_max_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.aft3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean aft3_max_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean max_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.line
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    private Boolean line;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_id
     *
     * @return the value of ticket.ticket_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Integer getTicket_id() {
        return ticket_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_id
     *
     * @param ticket_id the value for ticket.ticket_id
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setTicket_id(Integer ticket_id) {
        this.ticket_id = ticket_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_no
     *
     * @return the value of ticket.ticket_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public String getTicket_no() {
        return ticket_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_no
     *
     * @param ticket_no the value for ticket.ticket_no
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setTicket_no(String ticket_no) {
        this.ticket_no = ticket_no == null ? null : ticket_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_num
     *
     * @return the value of ticket.ticket_num
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public String getTicket_num() {
        return ticket_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_num
     *
     * @param ticket_num the value for ticket.ticket_num
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setTicket_num(String ticket_num) {
        this.ticket_num = ticket_num == null ? null : ticket_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_date
     *
     * @return the value of ticket.ticket_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Date getTicket_date() {
        return ticket_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_date
     *
     * @param ticket_date the value for ticket.ticket_date
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setTicket_date(Date ticket_date) {
        this.ticket_date = ticket_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.bef3_max_count
     *
     * @return the value of ticket.bef3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getBef3_max_count() {
        return bef3_max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.bef3_max_count
     *
     * @param bef3_max_count the value for ticket.bef3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setBef3_max_count(Boolean bef3_max_count) {
        this.bef3_max_count = bef3_max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.mid3_max_count
     *
     * @return the value of ticket.mid3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getMid3_max_count() {
        return mid3_max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.mid3_max_count
     *
     * @param mid3_max_count the value for ticket.mid3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setMid3_max_count(Boolean mid3_max_count) {
        this.mid3_max_count = mid3_max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.aft3_max_count
     *
     * @return the value of ticket.aft3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getAft3_max_count() {
        return aft3_max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.aft3_max_count
     *
     * @param aft3_max_count the value for ticket.aft3_max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setAft3_max_count(Boolean aft3_max_count) {
        this.aft3_max_count = aft3_max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.max_count
     *
     * @return the value of ticket.max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getMax_count() {
        return max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.max_count
     *
     * @param max_count the value for ticket.max_count
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setMax_count(Boolean max_count) {
        this.max_count = max_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.line
     *
     * @return the value of ticket.line
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public Boolean getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.line
     *
     * @param line the value for ticket.line
     *
     * @mbg.generated Sun Sep 30 16:04:29 CST 2018
     */
    public void setLine(Boolean line) {
        this.line = line;
    }
}