server:
  port: 80
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: utf-8
spring:
  thymeleaf:
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
logback:
  # 日志根文件
  file: /usr/logs/analyze
self:
  data:
    # 数据抓取地址
    data-url: http://39.108.143.25:8080/stock/cqssc/getCurrentDay.sc
    # 豹子抓取地址
    bz-url: http://39.108.143.25:8080/stock/cqssc/getBzList.sc