package com.treasure.mbgenerator.mapper;

import com.treasure.mbgenerator.entity.Bz;
import com.treasure.mbgenerator.entity.BzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    long countByExample(BzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int deleteByExample(BzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int insert(Bz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int insertSelective(Bz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    List<Bz> selectByExample(BzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    Bz selectByPrimaryKey(Integer bzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bz record, @Param("example") BzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bz record, @Param("example") BzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bz record);
}