package com.treasure.mbgenerator.entity;

import java.util.Date;

public class Buy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.buy_id
     *
     * @mbg.generated
     */
    private Integer buyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.start_no
     *
     * @mbg.generated
     */
    private Short startNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.end_no
     *
     * @mbg.generated
     */
    private Short endNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.ticket_date
     *
     * @mbg.generated
     */
    private Date ticketDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.end_flag
     *
     * @mbg.generated
     */
    private Boolean endFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.buy_id
     *
     * @return the value of buy.buy_id
     *
     * @mbg.generated
     */
    public Integer getBuyId() {
        return buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.buy_id
     *
     * @param buyId the value for buy.buy_id
     *
     * @mbg.generated
     */
    public void setBuyId(Integer buyId) {
        this.buyId = buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.start_no
     *
     * @return the value of buy.start_no
     *
     * @mbg.generated
     */
    public Short getStartNo() {
        return startNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.start_no
     *
     * @param startNo the value for buy.start_no
     *
     * @mbg.generated
     */
    public void setStartNo(Short startNo) {
        this.startNo = startNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.end_no
     *
     * @return the value of buy.end_no
     *
     * @mbg.generated
     */
    public Short getEndNo() {
        return endNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.end_no
     *
     * @param endNo the value for buy.end_no
     *
     * @mbg.generated
     */
    public void setEndNo(Short endNo) {
        this.endNo = endNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.ticket_date
     *
     * @return the value of buy.ticket_date
     *
     * @mbg.generated
     */
    public Date getTicketDate() {
        return ticketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.ticket_date
     *
     * @param ticketDate the value for buy.ticket_date
     *
     * @mbg.generated
     */
    public void setTicketDate(Date ticketDate) {
        this.ticketDate = ticketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.end_flag
     *
     * @return the value of buy.end_flag
     *
     * @mbg.generated
     */
    public Boolean getEndFlag() {
        return endFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.end_flag
     *
     * @param endFlag the value for buy.end_flag
     *
     * @mbg.generated
     */
    public void setEndFlag(Boolean endFlag) {
        this.endFlag = endFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy.user_id
     *
     * @return the value of buy.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy.user_id
     *
     * @param userId the value for buy.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}