package com.treasure.mbgenerator.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bz
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public BzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bz
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bz
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andBzIdIsNull() {
            addCriterion("bz_id is null");
            return (Criteria) this;
        }

        public Criteria andBzIdIsNotNull() {
            addCriterion("bz_id is not null");
            return (Criteria) this;
        }

        public Criteria andBzIdEqualTo(Integer value) {
            addCriterion("bz_id =", value, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdNotEqualTo(Integer value) {
            addCriterion("bz_id <>", value, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdGreaterThan(Integer value) {
            addCriterion("bz_id >", value, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bz_id >=", value, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdLessThan(Integer value) {
            addCriterion("bz_id <", value, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdLessThanOrEqualTo(Integer value) {
            addCriterion("bz_id <=", value, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdIn(List<Integer> values) {
            addCriterion("bz_id in", values, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdNotIn(List<Integer> values) {
            addCriterion("bz_id not in", values, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdBetween(Integer value1, Integer value2) {
            addCriterion("bz_id between", value1, value2, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bz_id not between", value1, value2, "bzId");
            return (Criteria) this;
        }

        public Criteria andBzDateIsNull() {
            addCriterion("bz_date is null");
            return (Criteria) this;
        }

        public Criteria andBzDateIsNotNull() {
            addCriterion("bz_date is not null");
            return (Criteria) this;
        }

        public Criteria andBzDateEqualTo(Date value) {
            addCriterionForJDBCDate("bz_date =", value, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("bz_date <>", value, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateGreaterThan(Date value) {
            addCriterionForJDBCDate("bz_date >", value, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("bz_date >=", value, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateLessThan(Date value) {
            addCriterionForJDBCDate("bz_date <", value, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("bz_date <=", value, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateIn(List<Date> values) {
            addCriterionForJDBCDate("bz_date in", values, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("bz_date not in", values, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("bz_date between", value1, value2, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBzDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("bz_date not between", value1, value2, "bzDate");
            return (Criteria) this;
        }

        public Criteria andBsgIsNull() {
            addCriterion("bsg is null");
            return (Criteria) this;
        }

        public Criteria andBsgIsNotNull() {
            addCriterion("bsg is not null");
            return (Criteria) this;
        }

        public Criteria andBsgEqualTo(Short value) {
            addCriterion("bsg =", value, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgNotEqualTo(Short value) {
            addCriterion("bsg <>", value, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgGreaterThan(Short value) {
            addCriterion("bsg >", value, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgGreaterThanOrEqualTo(Short value) {
            addCriterion("bsg >=", value, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgLessThan(Short value) {
            addCriterion("bsg <", value, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgLessThanOrEqualTo(Short value) {
            addCriterion("bsg <=", value, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgIn(List<Short> values) {
            addCriterion("bsg in", values, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgNotIn(List<Short> values) {
            addCriterion("bsg not in", values, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgBetween(Short value1, Short value2) {
            addCriterion("bsg between", value1, value2, "bsg");
            return (Criteria) this;
        }

        public Criteria andBsgNotBetween(Short value1, Short value2) {
            addCriterion("bsg not between", value1, value2, "bsg");
            return (Criteria) this;
        }

        public Criteria andQbgIsNull() {
            addCriterion("qbg is null");
            return (Criteria) this;
        }

        public Criteria andQbgIsNotNull() {
            addCriterion("qbg is not null");
            return (Criteria) this;
        }

        public Criteria andQbgEqualTo(Short value) {
            addCriterion("qbg =", value, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgNotEqualTo(Short value) {
            addCriterion("qbg <>", value, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgGreaterThan(Short value) {
            addCriterion("qbg >", value, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgGreaterThanOrEqualTo(Short value) {
            addCriterion("qbg >=", value, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgLessThan(Short value) {
            addCriterion("qbg <", value, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgLessThanOrEqualTo(Short value) {
            addCriterion("qbg <=", value, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgIn(List<Short> values) {
            addCriterion("qbg in", values, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgNotIn(List<Short> values) {
            addCriterion("qbg not in", values, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgBetween(Short value1, Short value2) {
            addCriterion("qbg between", value1, value2, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbgNotBetween(Short value1, Short value2) {
            addCriterion("qbg not between", value1, value2, "qbg");
            return (Criteria) this;
        }

        public Criteria andQbsIsNull() {
            addCriterion("qbs is null");
            return (Criteria) this;
        }

        public Criteria andQbsIsNotNull() {
            addCriterion("qbs is not null");
            return (Criteria) this;
        }

        public Criteria andQbsEqualTo(Short value) {
            addCriterion("qbs =", value, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsNotEqualTo(Short value) {
            addCriterion("qbs <>", value, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsGreaterThan(Short value) {
            addCriterion("qbs >", value, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsGreaterThanOrEqualTo(Short value) {
            addCriterion("qbs >=", value, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsLessThan(Short value) {
            addCriterion("qbs <", value, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsLessThanOrEqualTo(Short value) {
            addCriterion("qbs <=", value, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsIn(List<Short> values) {
            addCriterion("qbs in", values, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsNotIn(List<Short> values) {
            addCriterion("qbs not in", values, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsBetween(Short value1, Short value2) {
            addCriterion("qbs between", value1, value2, "qbs");
            return (Criteria) this;
        }

        public Criteria andQbsNotBetween(Short value1, Short value2) {
            addCriterion("qbs not between", value1, value2, "qbs");
            return (Criteria) this;
        }

        public Criteria andQsgIsNull() {
            addCriterion("qsg is null");
            return (Criteria) this;
        }

        public Criteria andQsgIsNotNull() {
            addCriterion("qsg is not null");
            return (Criteria) this;
        }

        public Criteria andQsgEqualTo(Short value) {
            addCriterion("qsg =", value, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgNotEqualTo(Short value) {
            addCriterion("qsg <>", value, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgGreaterThan(Short value) {
            addCriterion("qsg >", value, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgGreaterThanOrEqualTo(Short value) {
            addCriterion("qsg >=", value, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgLessThan(Short value) {
            addCriterion("qsg <", value, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgLessThanOrEqualTo(Short value) {
            addCriterion("qsg <=", value, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgIn(List<Short> values) {
            addCriterion("qsg in", values, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgNotIn(List<Short> values) {
            addCriterion("qsg not in", values, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgBetween(Short value1, Short value2) {
            addCriterion("qsg between", value1, value2, "qsg");
            return (Criteria) this;
        }

        public Criteria andQsgNotBetween(Short value1, Short value2) {
            addCriterion("qsg not between", value1, value2, "qsg");
            return (Criteria) this;
        }

        public Criteria andWbgIsNull() {
            addCriterion("wbg is null");
            return (Criteria) this;
        }

        public Criteria andWbgIsNotNull() {
            addCriterion("wbg is not null");
            return (Criteria) this;
        }

        public Criteria andWbgEqualTo(Short value) {
            addCriterion("wbg =", value, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgNotEqualTo(Short value) {
            addCriterion("wbg <>", value, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgGreaterThan(Short value) {
            addCriterion("wbg >", value, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgGreaterThanOrEqualTo(Short value) {
            addCriterion("wbg >=", value, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgLessThan(Short value) {
            addCriterion("wbg <", value, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgLessThanOrEqualTo(Short value) {
            addCriterion("wbg <=", value, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgIn(List<Short> values) {
            addCriterion("wbg in", values, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgNotIn(List<Short> values) {
            addCriterion("wbg not in", values, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgBetween(Short value1, Short value2) {
            addCriterion("wbg between", value1, value2, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbgNotBetween(Short value1, Short value2) {
            addCriterion("wbg not between", value1, value2, "wbg");
            return (Criteria) this;
        }

        public Criteria andWbsIsNull() {
            addCriterion("wbs is null");
            return (Criteria) this;
        }

        public Criteria andWbsIsNotNull() {
            addCriterion("wbs is not null");
            return (Criteria) this;
        }

        public Criteria andWbsEqualTo(Short value) {
            addCriterion("wbs =", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotEqualTo(Short value) {
            addCriterion("wbs <>", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsGreaterThan(Short value) {
            addCriterion("wbs >", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsGreaterThanOrEqualTo(Short value) {
            addCriterion("wbs >=", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsLessThan(Short value) {
            addCriterion("wbs <", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsLessThanOrEqualTo(Short value) {
            addCriterion("wbs <=", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsIn(List<Short> values) {
            addCriterion("wbs in", values, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotIn(List<Short> values) {
            addCriterion("wbs not in", values, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsBetween(Short value1, Short value2) {
            addCriterion("wbs between", value1, value2, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotBetween(Short value1, Short value2) {
            addCriterion("wbs not between", value1, value2, "wbs");
            return (Criteria) this;
        }

        public Criteria andWqbIsNull() {
            addCriterion("wqb is null");
            return (Criteria) this;
        }

        public Criteria andWqbIsNotNull() {
            addCriterion("wqb is not null");
            return (Criteria) this;
        }

        public Criteria andWqbEqualTo(Short value) {
            addCriterion("wqb =", value, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbNotEqualTo(Short value) {
            addCriterion("wqb <>", value, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbGreaterThan(Short value) {
            addCriterion("wqb >", value, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbGreaterThanOrEqualTo(Short value) {
            addCriterion("wqb >=", value, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbLessThan(Short value) {
            addCriterion("wqb <", value, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbLessThanOrEqualTo(Short value) {
            addCriterion("wqb <=", value, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbIn(List<Short> values) {
            addCriterion("wqb in", values, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbNotIn(List<Short> values) {
            addCriterion("wqb not in", values, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbBetween(Short value1, Short value2) {
            addCriterion("wqb between", value1, value2, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqbNotBetween(Short value1, Short value2) {
            addCriterion("wqb not between", value1, value2, "wqb");
            return (Criteria) this;
        }

        public Criteria andWqgIsNull() {
            addCriterion("wqg is null");
            return (Criteria) this;
        }

        public Criteria andWqgIsNotNull() {
            addCriterion("wqg is not null");
            return (Criteria) this;
        }

        public Criteria andWqgEqualTo(Short value) {
            addCriterion("wqg =", value, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgNotEqualTo(Short value) {
            addCriterion("wqg <>", value, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgGreaterThan(Short value) {
            addCriterion("wqg >", value, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgGreaterThanOrEqualTo(Short value) {
            addCriterion("wqg >=", value, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgLessThan(Short value) {
            addCriterion("wqg <", value, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgLessThanOrEqualTo(Short value) {
            addCriterion("wqg <=", value, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgIn(List<Short> values) {
            addCriterion("wqg in", values, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgNotIn(List<Short> values) {
            addCriterion("wqg not in", values, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgBetween(Short value1, Short value2) {
            addCriterion("wqg between", value1, value2, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqgNotBetween(Short value1, Short value2) {
            addCriterion("wqg not between", value1, value2, "wqg");
            return (Criteria) this;
        }

        public Criteria andWqsIsNull() {
            addCriterion("wqs is null");
            return (Criteria) this;
        }

        public Criteria andWqsIsNotNull() {
            addCriterion("wqs is not null");
            return (Criteria) this;
        }

        public Criteria andWqsEqualTo(Short value) {
            addCriterion("wqs =", value, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsNotEqualTo(Short value) {
            addCriterion("wqs <>", value, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsGreaterThan(Short value) {
            addCriterion("wqs >", value, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsGreaterThanOrEqualTo(Short value) {
            addCriterion("wqs >=", value, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsLessThan(Short value) {
            addCriterion("wqs <", value, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsLessThanOrEqualTo(Short value) {
            addCriterion("wqs <=", value, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsIn(List<Short> values) {
            addCriterion("wqs in", values, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsNotIn(List<Short> values) {
            addCriterion("wqs not in", values, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsBetween(Short value1, Short value2) {
            addCriterion("wqs between", value1, value2, "wqs");
            return (Criteria) this;
        }

        public Criteria andWqsNotBetween(Short value1, Short value2) {
            addCriterion("wqs not between", value1, value2, "wqs");
            return (Criteria) this;
        }

        public Criteria andWsgIsNull() {
            addCriterion("wsg is null");
            return (Criteria) this;
        }

        public Criteria andWsgIsNotNull() {
            addCriterion("wsg is not null");
            return (Criteria) this;
        }

        public Criteria andWsgEqualTo(Short value) {
            addCriterion("wsg =", value, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgNotEqualTo(Short value) {
            addCriterion("wsg <>", value, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgGreaterThan(Short value) {
            addCriterion("wsg >", value, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgGreaterThanOrEqualTo(Short value) {
            addCriterion("wsg >=", value, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgLessThan(Short value) {
            addCriterion("wsg <", value, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgLessThanOrEqualTo(Short value) {
            addCriterion("wsg <=", value, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgIn(List<Short> values) {
            addCriterion("wsg in", values, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgNotIn(List<Short> values) {
            addCriterion("wsg not in", values, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgBetween(Short value1, Short value2) {
            addCriterion("wsg between", value1, value2, "wsg");
            return (Criteria) this;
        }

        public Criteria andWsgNotBetween(Short value1, Short value2) {
            addCriterion("wsg not between", value1, value2, "wsg");
            return (Criteria) this;
        }

        public Criteria andWxzsIsNull() {
            addCriterion("wxzs is null");
            return (Criteria) this;
        }

        public Criteria andWxzsIsNotNull() {
            addCriterion("wxzs is not null");
            return (Criteria) this;
        }

        public Criteria andWxzsEqualTo(Short value) {
            addCriterion("wxzs =", value, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsNotEqualTo(Short value) {
            addCriterion("wxzs <>", value, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsGreaterThan(Short value) {
            addCriterion("wxzs >", value, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsGreaterThanOrEqualTo(Short value) {
            addCriterion("wxzs >=", value, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsLessThan(Short value) {
            addCriterion("wxzs <", value, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsLessThanOrEqualTo(Short value) {
            addCriterion("wxzs <=", value, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsIn(List<Short> values) {
            addCriterion("wxzs in", values, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsNotIn(List<Short> values) {
            addCriterion("wxzs not in", values, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsBetween(Short value1, Short value2) {
            addCriterion("wxzs between", value1, value2, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzsNotBetween(Short value1, Short value2) {
            addCriterion("wxzs not between", value1, value2, "wxzs");
            return (Criteria) this;
        }

        public Criteria andWxzwIsNull() {
            addCriterion("wxzw is null");
            return (Criteria) this;
        }

        public Criteria andWxzwIsNotNull() {
            addCriterion("wxzw is not null");
            return (Criteria) this;
        }

        public Criteria andWxzwEqualTo(Short value) {
            addCriterion("wxzw =", value, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwNotEqualTo(Short value) {
            addCriterion("wxzw <>", value, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwGreaterThan(Short value) {
            addCriterion("wxzw >", value, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwGreaterThanOrEqualTo(Short value) {
            addCriterion("wxzw >=", value, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwLessThan(Short value) {
            addCriterion("wxzw <", value, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwLessThanOrEqualTo(Short value) {
            addCriterion("wxzw <=", value, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwIn(List<Short> values) {
            addCriterion("wxzw in", values, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwNotIn(List<Short> values) {
            addCriterion("wxzw not in", values, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwBetween(Short value1, Short value2) {
            addCriterion("wxzw between", value1, value2, "wxzw");
            return (Criteria) this;
        }

        public Criteria andWxzwNotBetween(Short value1, Short value2) {
            addCriterion("wxzw not between", value1, value2, "wxzw");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bz
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bz
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}