package com.treasure.mbgenerator.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SscUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.now_no
     *
     * @mbg.generated
     */
    private String nowNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssc_user.now_date
     *
     * @mbg.generated
     */
    private Date nowDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.user_id
     *
     * @return the value of ssc_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.user_id
     *
     * @param userId the value for ssc_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.username
     *
     * @return the value of ssc_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.username
     *
     * @param username the value for ssc_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.money
     *
     * @return the value of ssc_user.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.money
     *
     * @param money the value for ssc_user.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.create_time
     *
     * @return the value of ssc_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.create_time
     *
     * @param createTime the value for ssc_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.update_time
     *
     * @return the value of ssc_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.update_time
     *
     * @param updateTime the value for ssc_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.now_no
     *
     * @return the value of ssc_user.now_no
     *
     * @mbg.generated
     */
    public String getNowNo() {
        return nowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.now_no
     *
     * @param nowNo the value for ssc_user.now_no
     *
     * @mbg.generated
     */
    public void setNowNo(String nowNo) {
        this.nowNo = nowNo == null ? null : nowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssc_user.now_date
     *
     * @return the value of ssc_user.now_date
     *
     * @mbg.generated
     */
    public Date getNowDate() {
        return nowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssc_user.now_date
     *
     * @param nowDate the value for ssc_user.now_date
     *
     * @mbg.generated
     */
    public void setNowDate(Date nowDate) {
        this.nowDate = nowDate;
    }
}