package com.treasure.auto.mapper;

import com.treasure.auto.entity.BuyItem;
import com.treasure.auto.entity.BuyItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    long countByExample(BuyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int deleteByExample(BuyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buyItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int insert(BuyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int insertSelective(BuyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    List<BuyItem> selectByExample(BuyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    BuyItem selectByPrimaryKey(Integer buyItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BuyItem record, @Param("example") BuyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BuyItem record, @Param("example") BuyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BuyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BuyItem record);
}