package com.treasure.auto.mapper;

import com.treasure.auto.entity.Buy;
import com.treasure.auto.entity.BuyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    long countByExample(BuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int deleteByExample(BuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int insert(Buy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int insertSelective(Buy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    List<Buy> selectByExample(BuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    Buy selectByPrimaryKey(Integer buyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Buy record, @Param("example") BuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Buy record, @Param("example") BuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Buy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Buy record);
}