package com.treasure.auto.mapper;

import com.treasure.auto.entity.SscUser;
import com.treasure.auto.entity.SscUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SscUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    long countByExample(SscUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int deleteByExample(SscUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int insert(SscUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int insertSelective(SscUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    List<SscUser> selectByExample(SscUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    SscUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SscUser record, @Param("example") SscUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SscUser record, @Param("example") SscUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SscUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SscUser record);
}