server:
  port: 80
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: utf-8
spring:
  thymeleaf:
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
logback:
  # 日志根文件
  file: E:/usr/logs