server:
  port: 80
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: utf-8
spring:
  profiles:
    # 默认开发环境
    active: dev
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
logback:
  # 日志根文件
  file: E:/usr/logs