server:
  port: 80
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: utf-8
spring:
  thymeleaf:
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    ### 家里
    #url: jdbc:mysql://192.168.2.171:3306/red_myb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: Admin123!
    ### 公司
    url: jdbc:mysql://10.0.1.45:3306/red_myb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    open-in-view: false
logback:
  # 日志根文件
  file: /usr/logs/ssc
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:auto/mapper/*.xml
self:
  data:
    # 数据抓取地址
    data-url: http://39.108.143.25:8080/stock/cqssc/getCurrentDay.sc
    # 豹子抓取地址
    bz-url: http://39.108.143.25:8080/stock/cqssc/getBzList.sc